version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: chat-app
    environment:
      POSTGRES_USER: reon
      POSTGRES_PASSWORD: reon
      POSTGRES_DB: dbchatapp
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
